[platformio]
default_envs = T-Deck
src_dir = src
boards_dir = boards

[env:T-Deck]
platform = espressif32@6.3.0
board = T-Deck
framework = arduino
upload_speed = 921600
monitor_speed = 115200
build_flags =
    -DBOARD_HAS_PSRAM=1
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MOSI=41
    -DTFT_SCLK=40
    -DTFT_CS=12
    -DTFT_DC=11
    -DTFT_RST=-1
    -DTFT_BL=42
    -DTFT_BACKLIGHT_ON=1
    -DTFT_RGB_ORDER=0
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DSMOOTH_FONT=1
    -DSPI_FREQUENCY=40000000
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    jgromes/RadioLib@^6.0.0
